apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.role.instance }}"
  labels:
    app: {{ template "oic-collection-integration.name" . }}
    chart: {{ template "oic-collection-integration.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: oic-collection-integration-sa